`include "e203_defines.v"

`define CONV2D_CORE_NUMBER			25
`define CONV2D_IFMAP_DATA_WIDTH		8
`define CONV2D_OFMAP_DATA_WIDTH		32
`define CONV2D_KERNEL_SIZE			3

`define CONV2D_ADDR_SIZE			`E203_ADDR_SIZE

`define CONV2D_CHSEL_SIZE			32
`define CONV2D_CCR_SIZE				16
`define CONV2D_CPAR_SIZE			16
`define CONV2D_FILWR_SIZE			32

`define CONV2D_CCR_EN_SIZE			1
`define CONV2D_CCR_CLR_SIZE			1
`define CONV2D_CCR_IFRDY_SIZE		1
`define CONV2D_CCR_OFVLD_SIZE		1
`define CONV2D_CCR_IFRWD_SIZE		1
`define CONV2D_CCR_RESERVED_SIZE	11

`define CONV2D_CCR_EN_OFS			0:0
`define CONV2D_CCR_CLR_OFS			1:1
`define CONV2D_CCR_IFRDY_OFS		2:2
`define CONV2D_CCR_OFVLD_OFS		3:3
`define CONV2D_CCR_IFRWD_OFS		4:4
`define CONV2D_CCR_RESERVED_OFS		15:5

`define CONV2D_CPAR_STRSEL_SIZE		1
`define CONV2D_CPAR_DILSEL_SIZE		2
`define CONV2D_CPAR_MODSEL_SIZE		1
`define CONV2D_CPAR_RESACC_SIZE		1
`define CONV2D_CPAR_RESACT_SIZE		1
`define CONV2D_CPAR_IFSIZE_SIZE		2
`define CONV2D_CPAR_RESERVED_SIZE	8

`define CONV2D_CPAR_STRSEL_OFS		0:0
`define CONV2D_CPAR_DILSEL_OFS		2:1
`define CONV2D_CPAR_MODSEL_OFS		3:3
`define CONV2D_CPAR_RESACC_OFS		4:4
`define CONV2D_CPAR_RESACT_OFS		5:5
`define CONV2D_CPAR_IFSIZE_OFS		7:6
`define CONV2D_CPAR_RESERVED_OFS	15:8

`define CONV2D_CHSEL_ADDR			`CONV2D_ADDR_SIZE'h0000_0000
`define CONV2D_CCR_ADDR				`CONV2D_ADDR_SIZE'h0000_0004
`define CONV2D_CPAR_ADDR			`CONV2D_ADDR_SIZE'h0000_0006
`define CONV2D_IFWR_ADDR			`CONV2D_ADDR_SIZE'h0000_0008
`define CONV2D_OFRD_ADDR			`CONV2D_ADDR_SIZE'h0000_000C
`define CONV2D_FILWR_ADDR			`CONV2D_ADDR_SIZE'h0000_0010
`define CONV2D_CDONE_ADDR			`CONV2D_ADDR_SIZE'h0000_0014
`define CONV2D_OFCNT_ADDR			`CONV2D_ADDR_SIZE'h0000_0018

`define CONV2D_CHSEL_ADDR_SIZE		4
`define CONV2D_CCR_ADDR_SIZE		2
`define CONV2D_CPAR_ADDR_SIZE		2
`define CONV2D_IFWR_ADDR_SIZE		4
`define CONV2D_OFRD_ADDR_SIZE		4
`define CONV2D_FILWR_ADDR_SIZE		4
`define CONV2D_CDONE_ADDR_SIZE		4
`define CONV2D_OFCNT_ADDR_SIZE		2
