`include "e203_defines.v"

`define DMAC_ADDR_SIZE			`E203_ADDR_SIZE

`define DMAC_CCR_SIZE			16
`define DMAC_CSAR_SIZE			`DMAC_ADDR_SIZE			
`define DMAC_CDAR_SIZE			`DMAC_ADDR_SIZE
`define DMAC_CMDTR_SIZE			16

`define DMAC_CCR_ADDR_SIZE		(`DMAC_CCR_SIZE / 8)
`define DMAC_CSAR_ADDR_SIZE		(`DMAC_CSAR_SIZE / 8)			
`define DMAC_CDAR_ADDR_SIZE		(`DMAC_CDAR_SIZE / 8)
`define DMAC_CMDTR_ADDR_SIZE	(`DMAC_CMDTR_SIZE / 8)

`define DMAC_CCR_EN_SIZE		1
`define DMAC_CCR_IEN_SIZE		1
`define DMAC_CCR_TCIE_SIZE		1
`define DMAC_CCR_TEIE_SIZE		1
`define DMAC_CCR_DIR_SIZE		1
`define DMAC_CCR_CIRC_SIZE		1
`define DMAC_CCR_SINC_SIZE		1
`define DMAC_CCR_DINC_SIZE		1
`define DMAC_CCR_SSIZE_SIZE		2
`define DMAC_CCR_DSIZE_SIZE		2
`define DMAC_CCR_RESERVED_SIZE	4

`define DMAC_CCR_EN_OFS			0:0
`define DMAC_CCR_IEN_OFS		1:1
`define DMAC_CCR_TCIE_OFS		2:2
`define DMAC_CCR_TEIE_OFS		3:3
`define DMAC_CCR_DIR_OFS		4:4
`define DMAC_CCR_CIRC_OFS		5:5
`define DMAC_CCR_DINC_OFS		6:6
`define DMAC_CCR_SINC_OFS		7:7
`define DMAC_CCR_SSIZE_OFS		9:8
`define DMAC_CCR_DSIZE_OFS		11:10

`define DMAC_CCR_BASE			`DMAC_ADDR_SIZE'd0
`define DMAC_CSAR_BASE			`DMAC_ADDR_SIZE'd16
`define DMAC_CDAR_BASE			`DMAC_ADDR_SIZE'd48
`define DMAC_CMDTR_BASE			`DMAC_ADDR_SIZE'd80
