`include "e203_defines.v"

`define CONV2D_ADDR_SIZE			`E203_ADDR_SIZE

`define CONV2D_CCR_SIZE				16
`define CONV2D_CPAR_SIZE			16
`define CONV2D_FILWR_SIZE			32

`define CONV2D_CCR_EN_SIZE			1
`define CONV2D_CCR_CLR_SIZE			1
`define CONV2D_CCR_IFRDY_SIZE		1
`define CONV2D_CCR_OFVLD_SIZE		1
`define CONV2D_CCR_RESERVED_SIZE	4

`define CONV2D_CCR_EN_OFS			0:0
`define CONV2D_CCR_CLR_OFS			1:1
`define CONV2D_CCR_IFRDY_OFS		2:2
`define CONV2D_CCR_OFVLD_OFS		3:3
`define CONV2D_CCR_RESERVED_OFS		7:4

`define CONV2D_CCR_BASE_ADDR		`CONV2D_ADDR_SIZE'h0000_0000
`define CONV2D_CPAR_BASE_ADDR		`CONV2D_ADDR_SIZE'h0000_0002
`define CONV2D_IFWR_BASE_ADDR		`CONV2D_ADDR_SIZE'h0000_0004
`define CONV2D_OFRD_BASE_ADDR		`CONV2D_ADDR_SIZE'h0000_0008
`define CONV2D_FILWR_BASE_ADDR		`CONV2D_ADDR_SIZE'h0000_000C

`define CONV2D_DONE_BASE_ADDR		`CONV2D_ADDR_SIZE'h0000_0200

`define CONV2D_CCR_ADDR_SIZE		2
`define CONV2D_CPAR_ADDR_SIZE		2
`define CONV2D_IFWR_ADDR_SIZE		4
`define CONV2D_OFRD_ADDR_SIZE		4
`define CONV2D_FILWR_ADDR_SIZE		4
`define CONV2D_REGION_ADDR_SIZE		(`CONV2D_CCR_ADDR_SIZE + `CONV2D_CPAR_ADDR_SIZE + `CONV2D_IFWR_ADDR_SIZE + `CONV2D_OFRD_ADDR_SIZE + `CONV2D_FILWR_ADDR_SIZE)

