# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/SoC/e203_series/e203_base_V11/e203/e203.srcs/sources_1/ip/hdmi_ram_2_1/hdmi_ram_2.xci
# IP: The module: 'hdmi_ram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/SoC/e203_series/e203_base_V11/e203/e203.srcs/sources_1/ip/hdmi_ram_2_1/hdmi_ram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_ram_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Projects/SoC/e203_series/e203_base_V11/e203/e203.srcs/sources_1/ip/hdmi_ram_2_1/hdmi_ram_2.xci
# IP: The module: 'hdmi_ram_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/SoC/e203_series/e203_base_V11/e203/e203.srcs/sources_1/ip/hdmi_ram_2_1/hdmi_ram_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_ram_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
