create_clock -period 20.000 -name sys_clk_pin [get_ports clk_board]

#set_false_path -from [get_clocks clk_out1_mmcm] -to [get_clocks clk_out3_mmcm]
#set_false_path -from [get_clocks clk_out3_mmcm] -to [get_clocks clk_out1_mmcm]
#set_false_path -from [get_clocks clk_out1_mmcm] -to [get_clocks clk_pll_i]
#set_false_path -from [get_clocks clk_pll_i] -to [get_clocks clk_out1_mmcm]
set_false_path -from [get_clocks clk_out1_mmcm] -to [get_clocks clk_out1_video_pll]

set_false_path -from [get_ports ck_rst] -to [all_registers]

set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33} [get_ports clk_board]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_board_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets IOBUF_jtag_TCK/O]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ip_mmcm/inst/clk_in1_mmcm]


#####            rst define           #####

set_property PACKAGE_PIN H7 [get_ports ck_rst]

#####                spi define               #####
set_property PACKAGE_PIN AA22 [get_ports qspi_cs]
set_property PACKAGE_PIN AA23 [get_ports qspi_sck]
set_property PACKAGE_PIN Y25 [get_ports {qspi_dq[3]}]
set_property PACKAGE_PIN AA25 [get_ports {qspi_dq[2]}]
set_property PACKAGE_PIN W25 [get_ports {qspi_dq[1]}]
set_property PACKAGE_PIN Y26 [get_ports {qspi_dq[0]}]

#####               MCU JTAG define           #####
set_property PACKAGE_PIN AB26 [get_ports jd_0]
set_property PACKAGE_PIN AC26 [get_ports jd_1]
set_property PACKAGE_PIN AB24 [get_ports jd_2]
set_property PACKAGE_PIN AC24 [get_ports jd_3]
set_property PACKAGE_PIN AA24 [get_ports jd_4]
set_property PACKAGE_PIN AB25 [get_ports jd_5]

#####                gpio define              #####
set_property PACKAGE_PIN Y22 [get_ports gpio_31]
set_property PACKAGE_PIN Y23 [get_ports gpio_30]
set_property PACKAGE_PIN W21 [get_ports gpio_29]
set_property PACKAGE_PIN Y21 [get_ports gpio_28]
set_property PACKAGE_PIN V26 [get_ports gpio_27]
set_property PACKAGE_PIN W26 [get_ports gpio_26]
set_property PACKAGE_PIN U25 [get_ports gpio_25]
set_property PACKAGE_PIN U26 [get_ports gpio_24]
set_property PACKAGE_PIN V24 [get_ports gpio_23]
set_property PACKAGE_PIN W24 [get_ports gpio_22]
set_property PACKAGE_PIN V23 [get_ports gpio_21]
set_property PACKAGE_PIN W23 [get_ports gpio_20]
set_property PACKAGE_PIN V18 [get_ports gpio_19]
set_property PACKAGE_PIN W18 [get_ports gpio_18]
set_property PACKAGE_PIN U22 [get_ports gpio_17]
set_property PACKAGE_PIN V22 [get_ports gpio_16]
set_property PACKAGE_PIN U21 [get_ports gpio_15]
set_property PACKAGE_PIN V21 [get_ports gpio_14]
set_property PACKAGE_PIN T20 [get_ports gpio_13]
set_property PACKAGE_PIN U20 [get_ports gpio_12]
set_property PACKAGE_PIN T19 [get_ports gpio_11]
set_property PACKAGE_PIN U19 [get_ports gpio_10]
set_property PACKAGE_PIN H21 [get_ports gpio_9]
set_property PACKAGE_PIN H22 [get_ports gpio_8]
set_property PACKAGE_PIN K21 [get_ports gpio_7]
set_property PACKAGE_PIN J21 [get_ports gpio_6]
set_property PACKAGE_PIN H26 [get_ports gpio_5]
set_property PACKAGE_PIN G26 [get_ports gpio_4]
set_property PACKAGE_PIN G25 [get_ports gpio_3]
set_property PACKAGE_PIN F25 [get_ports gpio_2]
set_property PACKAGE_PIN G20 [get_ports gpio_1]
set_property PACKAGE_PIN G21 [get_ports gpio_0]

set_property IOSTANDARD LVCMOS33 [get_ports ck_rst]

#####                spi define               #####
set_property IOSTANDARD LVCMOS33 [get_ports qspi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_sck]
set_property IOSTANDARD LVCMOS33 [get_ports {qspi_dq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {qspi_dq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {qspi_dq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {qspi_dq[0]}]

#####               MCU JTAG define           #####
set_property IOSTANDARD LVCMOS33 [get_ports jd_0]
set_property IOSTANDARD LVCMOS33 [get_ports jd_1]
set_property IOSTANDARD LVCMOS33 [get_ports jd_2]
set_property IOSTANDARD LVCMOS33 [get_ports jd_3]
set_property IOSTANDARD LVCMOS33 [get_ports jd_4]
set_property IOSTANDARD LVCMOS33 [get_ports jd_5]

#####                gpio define              #####
set_property IOSTANDARD LVCMOS33 [get_ports gpio_31]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_30]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_29]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_28]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_27]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_26]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_25]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_24]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_23]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_22]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_21]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_20]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_19]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_18]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_17]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_16]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_15]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_14]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_13]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_12]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_11]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_10]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_9]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_8]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_7]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_6]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_5]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_4]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_3]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_2]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_1]
set_property IOSTANDARD LVCMOS33 [get_ports gpio_0]

set_property IOSTANDARD LVCMOS33 [get_ports init_calib_complete]
set_property PACKAGE_PIN J6 [get_ports init_calib_complete]

set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dqs_p[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dqs_n[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dqs_p[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dqs_n[1]}]

set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[2]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[3]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[4]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[5]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[6]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[7]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[8]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[9]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[10]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[11]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[12]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[13]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[14]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddr3_dq[15]}]

############## HDMIOUT define##################
#set_property PACKAGE_PIN C4 [get_ports TMDS_clk_n]
#set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_n]
#set_property PACKAGE_PIN D4 [get_ports TMDS_clk_p]
#set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_p]

#set_property PACKAGE_PIN D1 [get_ports {TMDS_data_n[0]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[0]}]
#set_property PACKAGE_PIN E1 [get_ports {TMDS_data_p[0]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[0]}]

#set_property PACKAGE_PIN E2 [get_ports {TMDS_data_n[1]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[1]}]
#set_property PACKAGE_PIN F2 [get_ports {TMDS_data_p[1]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[1]}]

#set_property PACKAGE_PIN G1 [get_ports {TMDS_data_n[2]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[2]}]
#set_property PACKAGE_PIN G2 [get_ports {TMDS_data_p[2]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[2]}]



#####         SPI Configurate Setting        #######
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
